// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using website_dangky_laodong.Data;

#nullable disable

namespace website_dangky_laodong.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("website_dangky_laodong.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoa"));

                    b.Property<string>("TenKhoa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("website_dangky_laodong.Models.LaoDongCaNhan", b =>
                {
                    b.Property<int>("MaLDCaNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLDCaNhan"));

                    b.Property<string>("BuoiLaoDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MaTuanLaoDong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLaoDong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLDCaNhan");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTuanLaoDong");

                    b.ToTable("LaoDongCaNhans");
                });

            modelBuilder.Entity("website_dangky_laodong.Models.LaoDongLop", b =>
                {
                    b.Property<int>("MaLDLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLDLop"));

                    b.Property<string>("BuoiLaoDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MaTuanLaoDong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLaoDong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLDLop");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTuanLaoDong");

                    b.ToTable("LaoDongLops");
                });

            modelBuilder.Entity("website_dangky_laodong.Models.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<int?>("MaKhoa")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoa");

                    b.ToTable("Lops");
                });

            modelBuilder.Entity("website_dangky_laodong.Models.NguoiDung", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNguoiDung")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaLop");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("website_dangky_laodong.Models.TuanLaoDong", b =>
                {
                    b.Property<int>("MaTuanLaoDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTuanLaoDong"));

                    b.Property<string>("LoaiLaoDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTuan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTuanLaoDong");

                    b.ToTable("TuanLaoDongs");
                });

            modelBuilder.Entity("website_dangky_laodong.Models.LaoDongCaNhan", b =>
                {
                    b.HasOne("website_dangky_laodong.Models.Lop", "Lop")
                        .WithMany("LaoDongCaNhans")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("website_dangky_laodong.Models.NguoiDung", "NguoiDung")
                        .WithMany("LaoDongCaNhans")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("website_dangky_laodong.Models.TuanLaoDong", "TuanLaoDong")
                        .WithMany("LaoDongCaNhans")
                        .HasForeignKey("MaTuanLaoDong")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Lop");

                    b.Navigation("NguoiDung");

                    b.Navigation("TuanLaoDong");
                });

            modelBuilder.Entity("website_dangky_laodong.Models.LaoDongLop", b =>
                {
                    b.HasOne("website_dangky_laodong.Models.Lop", "Lop")
                        .WithMany("LaoDongLops")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("website_dangky_laodong.Models.NguoiDung", "NguoiDung")
                        .WithMany("LaoDongLops")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("website_dangky_laodong.Models.TuanLaoDong", "TuanLaoDong")
                        .WithMany("LaoDongLops")
                        .HasForeignKey("MaTuanLaoDong")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Lop");

                    b.Navigation("NguoiDung");

                    b.Navigation("TuanLaoDong");
                });

            modelBuilder.Entity("website_dangky_laodong.Models.Lop", b =>
                {
                    b.HasOne("website_dangky_laodong.Models.Khoa", "Khoa")
                        .WithMany("Lops")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("website_dangky_laodong.Models.NguoiDung", b =>
                {
                    b.HasOne("website_dangky_laodong.Models.Lop", "Lop")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("website_dangky_laodong.Models.Khoa", b =>
                {
                    b.Navigation("Lops");
                });

            modelBuilder.Entity("website_dangky_laodong.Models.Lop", b =>
                {
                    b.Navigation("LaoDongCaNhans");

                    b.Navigation("LaoDongLops");

                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("website_dangky_laodong.Models.NguoiDung", b =>
                {
                    b.Navigation("LaoDongCaNhans");

                    b.Navigation("LaoDongLops");
                });

            modelBuilder.Entity("website_dangky_laodong.Models.TuanLaoDong", b =>
                {
                    b.Navigation("LaoDongCaNhans");

                    b.Navigation("LaoDongLops");
                });
#pragma warning restore 612, 618
        }
    }
}
